import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { WatchlistManager } from '../monitoring/WatchlistManager';
import { MonitoringAlert } from '../monitoring/types';

export const AlertCenter: React.FC = () => {
  const navigate = useNavigate();
  const manager = WatchlistManager.getInstance();
  const [alerts, setAlerts] = useState<MonitoringAlert[]>(manager.getAlerts());
  const [filter, setFilter] = useState<string>('all');

  useEffect(() => {
    const unsub = manager.onAlert((newAlert) => {
      setAlerts((prev) => [newAlert, ...prev]);
    });
    return unsub;
  }, [manager]);

  const handleMarkAllRead = () => {
    alerts.forEach((a) => {
      if (!a.is_acknowledged) {
        manager.acknowledgeAlert(a.id);
      }
    });
    setAlerts([...manager.getAlerts()]);
  };

  const filteredAlerts = alerts.filter((a) => {
    if (filter === 'unread') return !a.is_acknowledged;
    if (filter === 'critical') return a.severity === 'CRITICAL';
    return true;
  });

  const getSeverityStyle = (sev: string) => {
    switch (sev) {
      case 'CRITICAL':
        return 'bg-error/20 text-error border-error/30';
      case 'HIGH':
        return 'bg-amber-500/20 text-amber-400 border-amber-500/30';
      case 'MEDIUM':
        return 'bg-primary/20 text-primary border-primary/30';
      default:
        return 'bg-surface-variant text-on-surface-variant border-outline-variant';
    }
  };

  return (
    <div className="max-w-[1600px] mx-auto space-y-6">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end border-b border-outline-variant pb-4 gap-4">
        <div>
          <div className="flex items-center gap-2 text-[11px] mb-1">
            <span className="font-sans text-outline uppercase tracking-widest">Operations</span>
            <span className="text-outline">/</span>
            <span className="font-sans text-primary uppercase tracking-widest">Alerts</span>
          </div>
          <h2 className="text-[22px] font-semibold text-on-surface leading-tight tracking-tight flex items-center gap-3">
            <span className="material-symbols-outlined text-error text-[26px]">notifications_active</span>
            Investigative Alert Center & Triage Queue
          </h2>
          <p className="text-on-surface-variant mt-1 text-xs">
            Live blockchain surveillance triggers generated by active watchlists, mixer exposure heuristics, and high-velocity fund sweeps.
          </p>
        </div>

        <div className="flex items-center gap-2">
          {/* Filters */}
          <div className="flex items-center bg-surface-container border border-outline-variant rounded p-0.5 text-xs font-mono">
            <button
              onClick={() => setFilter('all')}
              className={`px-2.5 py-1 rounded transition-colors ${
                filter === 'all' ? 'bg-primary/20 text-primary font-bold' : 'text-outline hover:text-on-surface'
              }`}
            >
              All ({alerts.length})
            </button>
            <button
              onClick={() => setFilter('unread')}
              className={`px-2.5 py-1 rounded transition-colors ${
                filter === 'unread' ? 'bg-primary/20 text-primary font-bold' : 'text-outline hover:text-on-surface'
              }`}
            >
              Unacknowledged ({alerts.filter((a) => !a.is_acknowledged).length})
            </button>
            <button
              onClick={() => setFilter('critical')}
              className={`px-2.5 py-1 rounded transition-colors ${
                filter === 'critical' ? 'bg-error/20 text-error font-bold' : 'text-outline hover:text-on-surface'
              }`}
            >
              Critical ({alerts.filter((a) => a.severity === 'CRITICAL').length})
            </button>
          </div>

          <button
            onClick={handleMarkAllRead}
            className="btn-secondary px-3.5 py-1.5 text-xs rounded flex items-center gap-1.5"
          >
            <span className="material-symbols-outlined text-[16px]">done_all</span>
            Mark All Read
          </button>
        </div>
      </div>

      {/* Alert Cards List */}
      <div className="space-y-3">
        {filteredAlerts.length === 0 ? (
          <div className="surface-level-1 border border-outline-variant rounded-lg p-12 text-center space-y-3 shadow-sm">
            <div className="w-12 h-12 rounded-full bg-primary/10 border border-primary/20 flex items-center justify-center text-primary mx-auto">
              <span className="material-symbols-outlined text-[24px]">verified</span>
            </div>
            <h3 className="text-sm font-semibold text-on-surface">No Active Alerts In Queue</h3>
            <p className="text-xs text-on-surface-variant max-w-md mx-auto">
              All monitored wallets are operating within established behavioral baselines. Live on-chain heuristics and RPC polling streams are actively listening for transaction events.
            </p>
            <div className="pt-2">
              <button
                onClick={() => navigate('/monitoring')}
                className="btn-primary text-xs px-4 py-1.5 rounded inline-flex items-center gap-1.5"
              >
                <span className="material-symbols-outlined text-[16px]">visibility</span>
                Manage Surveillance Watchlist
              </button>
            </div>
          </div>
        ) : (
          filteredAlerts.map((alert) => (
            <div
              key={alert.id}
              className={`surface-level-1 border rounded-lg p-5 flex flex-col md:flex-row items-start justify-between shadow-sm transition-colors gap-4 ${
                !alert.is_acknowledged ? 'border-primary/40 bg-primary/[0.015]' : 'border-outline-variant opacity-85'
              }`}
            >
              <div className="space-y-2 max-w-3xl">
                <div className="flex items-center gap-3 flex-wrap">
                  <span className={`text-[10px] font-bold font-mono px-2 py-0.5 rounded border ${getSeverityStyle(alert.severity)}`}>
                    {alert.severity}
                  </span>
                  <span className="text-xs font-bold text-on-surface">{alert.title}</span>
                  <span className="text-[11px] text-outline font-mono">({alert.id})</span>
                  <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-surface-container border border-outline-variant text-outline">
                    {alert.alert_type}
                  </span>
                </div>

                <p className="text-xs text-on-surface-variant leading-relaxed">
                  {alert.description}
                </p>

                <div className="flex items-center gap-4 text-xs font-mono text-outline pt-1 flex-wrap">
                  <span>Case: <span onClick={() => navigate(`/graph/${alert.case}`)} className="text-primary hover:underline cursor-pointer">{alert.case}</span></span>
                  <span>•</span>
                  <span>Target: <span onClick={() => navigate(`/wallet/${alert.wallet}`)} className="text-on-surface hover:underline cursor-pointer">{alert.wallet}</span></span>
                  <span>•</span>
                  <span>{new Date(alert.timestamp).toLocaleString()}</span>
                  {alert.tx_hash && (
                    <>
                      <span>•</span>
                      <span className="text-outline">Tx: <span className="text-primary truncate">{alert.tx_hash.slice(0, 10)}...</span></span>
                    </>
                  )}
                </div>
              </div>

              <div className="flex flex-row md:flex-col gap-2 shrink-0">
                <button
                  onClick={() => navigate(`/graph/${alert.case}`)}
                  className="btn-primary text-xs px-3.5 py-1.5 rounded flex items-center gap-1.5"
                >
                  <span className="material-symbols-outlined text-[16px]">account_tree</span>
                  Inspect in Graph
                </button>
                <button
                  onClick={() => navigate(`/wallet/${alert.wallet}`)}
                  className="btn-secondary text-xs px-3.5 py-1.5 rounded flex items-center gap-1.5"
                >
                  <span className="material-symbols-outlined text-[16px]">shield</span>
                  Analyze Wallet
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
